on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

name: Audit

jobs:
  rust-audit:
    name: Rust Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
